name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-dev build-essential git libstdc++6
          pip install --upgrade pip
          pip install Cython
          pip install kivy buildozer

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Build APK using Buildozer
        run: |
          buildozer android debug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pong-ai-game-apk
          path: bin/*.apk
          
